#!/usr/bin/env python3
"""Deterministic Prompt 017 self-hosting certification fixture.

The fixture is entirely in memory and performs no network or repository writes.
It proves the self-hosting process succeeds while certification fails safely when
legacy scenario evidence lacks an immutable framework revision.
"""
from __future__ import annotations

import hashlib
import json
from typing import Any

import yaml

FRAMEWORK_REVISION = "c0f779eedc97963283e2798a988c628df63ddcbe"
EVIDENCE_REVISION = "aceda4a01c27abcdca96bed3319cfa987a0272b5"
MISSION_ID = "self-host-ai-flywheel-certification"
GOAL_ID = "assemble-self-hosted-certification"
EXECUTION_ID = "EX-20260730T073000Z-001"
CERTIFICATION_ID = "CERT-20260730T074500Z-001"
READINESS_ID = "READINESS-20260730T074501Z-001"
PERSISTENCE_ID = "PERSIST-20260730T074502Z-001"


def normalized_yaml(value: Any) -> str:
    return yaml.safe_dump(value, sort_keys=False, allow_unicode=True, width=120)


def digest(value: Any) -> str:
    return hashlib.sha256(normalized_yaml(value).encode("utf-8")).hexdigest()


def snapshot(value: Any) -> dict[str, Any]:
    text = normalized_yaml(value)
    raw = text.encode("utf-8")
    return {
        "data": value,
        "yaml": text,
        "sha256": hashlib.sha256(raw).hexdigest(),
        "git_blob_sha": hashlib.sha1(f"blob {len(raw)}\0".encode() + raw).hexdigest(),
        "bytes": len(raw),
    }


def stage(started_at: str, completed_at: str, summary: str, refs: list[str]) -> dict[str, Any]:
    return {
        "status": "completed",
        "started_at": started_at,
        "completed_at": completed_at,
        "summary": summary,
        "refs": refs,
        "reason": None,
    }


scenario_specs = [
    {
        "id": 1,
        "name": "context-free-startup",
        "fixture_definition_refs": ["test/ai/prompts/001-startup-validation.md"],
        "result": "failed",
        "evidence_refs": ["test/ai/results/001-startup-validation.md"],
        "actual_result": "Historical verification passed, but the retained result and prompt do not identify the exact tested framework commit SHA; the evidence is insufficient for certification.",
        "source_revision": EVIDENCE_REVISION,
    },
    {
        "id": 2,
        "name": "first-execution",
        "fixture_definition_refs": ["test/ai/prompts/002-execution-creation.md"],
        "result": "failed",
        "evidence_refs": ["test/ai/results/002-execution-creation.md"],
        "actual_result": "Historical verification passed, but the retained result and prompt do not identify the exact tested framework commit SHA; the evidence is insufficient for certification.",
        "source_revision": EVIDENCE_REVISION,
    },
    {
        "id": 3,
        "name": "resume",
        "fixture_definition_refs": ["test/ai/prompts/011-resume-interrupted-execution.md"],
        "result": "passed",
        "evidence_refs": ["test/ai/results/011-resume-interrupted-execution.md"],
        "actual_result": "Interrupted execution resume passed at immutable framework revision 9f128c1c3aeb4a0fbdac9fcddaa95546539f0226.",
        "source_revision": "9f128c1c3aeb4a0fbdac9fcddaa95546539f0226",
    },
    {
        "id": 4,
        "name": "missing-artifact-recovery",
        "fixture_definition_refs": ["test/ai/prompts/014-recover-missing-required-artifact-launcher.md"],
        "result": "passed",
        "evidence_refs": ["test/ai/results/014-recover-missing-required-artifact.md"],
        "actual_result": "Missing required artifact recovery passed at immutable framework revision 923c46baf8d4bb400eef71a3507e07d797dcab87.",
        "source_revision": "923c46baf8d4bb400eef71a3507e07d797dcab87",
    },
    {
        "id": 5,
        "name": "broken-reference-recovery",
        "fixture_definition_refs": ["test/ai/prompts/015-recover-broken-active-reference-launcher.md"],
        "result": "passed",
        "evidence_refs": ["test/ai/results/015-recover-broken-active-reference.md"],
        "actual_result": "Broken active reference recovery passed at immutable framework revision 291f87fb4485a2cfaa4f1580a8157a2842d08317.",
        "source_revision": "291f87fb4485a2cfaa4f1580a8157a2842d08317",
    },
    {
        "id": 6,
        "name": "approval-boundary",
        "fixture_definition_refs": ["test/ai/prompts/013-enforce-approval-boundary.md"],
        "result": "passed",
        "evidence_refs": ["test/ai/results/013-enforce-approval-boundary.md"],
        "actual_result": "Approval boundary enforcement passed at immutable framework revision 7d18c1dacf02f341f0c464571bc2f99e78a4b4de.",
        "source_revision": "7d18c1dacf02f341f0c464571bc2f99e78a4b4de",
    },
    {
        "id": 7,
        "name": "lifecycle-completeness",
        "fixture_definition_refs": ["test/ai/prompts/010-end-to-end-execution.md"],
        "result": "passed",
        "evidence_refs": ["test/ai/results/010-end-to-end-execution.md"],
        "actual_result": "All eight lifecycle stages and terminal closure passed at immutable framework revision b79e505dbcc8dde9966ee581a124647b2d7fb08b.",
        "source_revision": "b79e505dbcc8dde9966ee581a124647b2d7fb08b",
    },
    {
        "id": 8,
        "name": "evidence-completeness",
        "fixture_definition_refs": ["test/ai/prompts/010-end-to-end-execution.md", "test/ai/prompts/016-run-representative-proving-mission-launcher.md"],
        "result": "passed",
        "evidence_refs": ["test/ai/results/010-end-to-end-execution.md", "test/ai/results/016-run-representative-proving-mission.md"],
        "actual_result": "Acceptance-criterion evidence mapping passed in the end-to-end lifecycle and representative proving mission results.",
        "source_revision": "1b90e6789109b6693ab0dc5d79dfb1b76cc74585",
    },
    {
        "id": 9,
        "name": "proving-mission",
        "fixture_definition_refs": ["test/ai/prompts/016-run-representative-proving-mission-launcher.md"],
        "result": "passed",
        "evidence_refs": ["test/ai/results/016-run-representative-proving-mission.md"],
        "actual_result": "Representative proving mission passed at immutable framework revision 1b90e6789109b6693ab0dc5d79dfb1b76cc74585.",
        "source_revision": "1b90e6789109b6693ab0dc5d79dfb1b76cc74585",
    },
    {
        "id": 10,
        "name": "self-hosting",
        "fixture_definition_refs": ["test/ai/prompts/017-self-host-certification.md"],
        "result": "passed",
        "evidence_refs": ["EVID-971", "EVID-972", EXECUTION_ID],
        "actual_result": "The framework used its own mission, goal, execution, evidence, validation, persistence, and approval-boundary contracts to evaluate certification and create corrective actions.",
        "source_revision": FRAMEWORK_REVISION,
    },
]

mission = {
    "schema_version": 1,
    "id": MISSION_ID,
    "title": "Self-Host AI Flywheel Certification",
    "status": "active",
    "objective": "Use the AI Flywheel operating model to assemble, validate, and govern its own certification package without bypassing evidence or human authority.",
    "constraints": [
        "Operate entirely in memory.",
        "Do not modify the framework repository or durable state.",
        "Do not treat chat history as certification evidence.",
        "Do not approve certification or readiness without durable human approval.",
    ],
    "success_criteria": [
        {
            "id": "MSC-970",
            "statement": "The self-hosting process produces a traceable certification decision, corrective actions for insufficient evidence, and no premature readiness transition.",
        }
    ],
    "goals": [GOAL_ID],
    "approvals_required": [],
}

goal = {
    "schema_version": 1,
    "id": GOAL_ID,
    "mission_id": MISSION_ID,
    "title": "Assemble Self-Hosted Certification",
    "status": "blocked",
    "objective": "Evaluate all ten certification scenarios with immutable evidence and prepare the certification and readiness records governed by the framework itself.",
    "depends_on": [],
    "blocked_by": ["Rerun Prompt 001 and Prompt 002 with exact immutable framework revisions."],
    "procedure": [
        "Read the certification and readiness contracts.",
        "Audit retained scenario evidence.",
        "Construct self-hosting execution, evidence, findings, validation, certification, readiness, and persistence artifacts.",
        "Block certification and readiness when immutable evidence is insufficient.",
    ],
    "acceptance_criteria": [
        {"id": "AC-970", "statement": "All ten certification scenarios are assessed against immutable evidence requirements."},
        {"id": "AC-971", "statement": "Certification, readiness, and persistence artifacts conform to their dedicated contracts."},
        {"id": "AC-972", "statement": "The framework uses its own mission, goal, execution, evidence, validation, classification, adaptation, persistence, and reuse capabilities."},
        {"id": "AC-973", "statement": "No approval, readiness transition, durable lifecycle transition, or repository mutation is invented."},
    ],
    "evidence_required": [
        {"criterion_id": "AC-970", "artifact_refs": ["EVID-970"]},
        {"criterion_id": "AC-971", "artifact_refs": ["EVID-971"]},
        {"criterion_id": "AC-972", "artifact_refs": ["EVID-972"]},
        {"criterion_id": "AC-973", "artifact_refs": ["EVID-973"]},
    ],
    "constraints": ["Read-only synthetic certification.", "Preserve the human approval boundary."],
    "approvals_required": [],
}

evidence_records = [
    {
        "schema_version": 1,
        "id": "EVID-970",
        "kind": "evidence",
        "mission_id": MISSION_ID,
        "goal_id": GOAL_ID,
        "execution_id": EXECUTION_ID,
        "created_at": "2026-07-30T07:31:00Z",
        "created_by": "chatgpt-session",
        "summary": "Certification scenario evidence audit.",
        "status": "accepted",
        "classification": "certification-evidence-audit",
        "criterion_ids": ["AC-970"],
        "source_refs": [item for scenario in scenario_specs for item in scenario["evidence_refs"]],
        "artifact_refs": [CERTIFICATION_ID],
        "evidence": {
            "evidence_type": "scenario-evidence-audit",
            "supported_claim": "Eight scenarios have sufficient immutable evidence and two legacy scenarios require rerun.",
            "source_or_method": "Independent review of retained prompt and result artifacts at the pinned testing revision.",
            "actual_result": "Scenarios 1 and 2 lack exact tested framework commit SHAs; scenarios 3 through 10 satisfy the fixture's evidence requirements.",
            "observed_at": "2026-07-30T07:31:00Z",
            "storage_location": "in-memory:EVID-970",
        },
    },
    {
        "schema_version": 1,
        "id": "EVID-971",
        "kind": "evidence",
        "mission_id": MISSION_ID,
        "goal_id": GOAL_ID,
        "execution_id": EXECUTION_ID,
        "created_at": "2026-07-30T07:32:00Z",
        "created_by": "chatgpt-session",
        "summary": "Certification artifact schema validation evidence.",
        "status": "accepted",
        "classification": "schema-validation",
        "criterion_ids": ["AC-971"],
        "source_refs": [
            ".flywheel/operating-model/schemas/certification-record.schema.yaml",
            ".flywheel/operating-model/schemas/readiness-validation.schema.yaml",
            ".flywheel/operating-model/schemas/persistence-plan.schema.yaml",
        ],
        "artifact_refs": [CERTIFICATION_ID, READINESS_ID, PERSISTENCE_ID],
        "evidence": {
            "evidence_type": "schema-validation",
            "supported_claim": "The proposed certification, readiness, and persistence artifacts use the dedicated schemas and semantic contracts.",
            "source_or_method": "JSON Schema Draft 2020-12 validation with YAML 1.2 parsing and format enforcement.",
            "actual_result": "All proposed artifacts are expected to validate; independent verification must confirm.",
            "observed_at": "2026-07-30T07:32:00Z",
            "storage_location": "in-memory:EVID-971",
        },
    },
    {
        "schema_version": 1,
        "id": "EVID-972",
        "kind": "evidence",
        "mission_id": MISSION_ID,
        "goal_id": GOAL_ID,
        "execution_id": EXECUTION_ID,
        "created_at": "2026-07-30T07:33:00Z",
        "created_by": "chatgpt-session",
        "summary": "Self-hosting artifact trace.",
        "status": "accepted",
        "classification": "self-hosting-proof",
        "criterion_ids": ["AC-972"],
        "source_refs": [MISSION_ID, GOAL_ID, EXECUTION_ID, PERSISTENCE_ID],
        "artifact_refs": ["DECISION-970", "FINDING-970", "FINDING-971", "REUSE-970"],
        "evidence": {
            "evidence_type": "cross-artifact-trace",
            "supported_claim": "The certification evaluation is represented by the framework's own operating artifacts.",
            "source_or_method": "Cross-reference validation of proposed mission, goal, execution, records, persistence plan, and reuse assessment.",
            "actual_result": "The complete self-hosting chain is present and preserves the evidence and approval boundaries.",
            "observed_at": "2026-07-30T07:33:00Z",
            "storage_location": "in-memory:EVID-972",
        },
    },
    {
        "schema_version": 1,
        "id": "EVID-973",
        "kind": "evidence",
        "mission_id": MISSION_ID,
        "goal_id": GOAL_ID,
        "execution_id": EXECUTION_ID,
        "created_at": "2026-07-30T07:34:00Z",
        "created_by": "chatgpt-session",
        "summary": "Repository and authority boundary evidence.",
        "status": "accepted",
        "classification": "immutability-and-authority",
        "criterion_ids": ["AC-973"],
        "source_refs": [FRAMEWORK_REVISION, EVIDENCE_REVISION],
        "artifact_refs": [READINESS_ID],
        "evidence": {
            "evidence_type": "boundary-verification",
            "supported_claim": "No repository mutation, approval, or readiness transition occurred.",
            "source_or_method": "Read-only connector inspection and in-memory artifact construction.",
            "actual_result": "Framework changes none; durable lifecycle transitions zero; approval reference null; proposed ready state null.",
            "observed_at": "2026-07-30T07:34:00Z",
            "storage_location": "in-memory:EVID-973",
        },
    },
]

finding_records = [
    {
        "schema_version": 1,
        "id": "FINDING-970",
        "kind": "finding",
        "mission_id": MISSION_ID,
        "goal_id": GOAL_ID,
        "execution_id": EXECUTION_ID,
        "created_at": "2026-07-30T07:35:00Z",
        "created_by": "chatgpt-session",
        "summary": "Prompt 001 certification evidence lacks an immutable framework revision.",
        "status": "open",
        "classification": "certification-evidence-gap",
        "criterion_ids": ["AC-970"],
        "source_refs": ["test/ai/results/001-startup-validation.md", "test/ai/prompts/001-startup-validation.md"],
        "artifact_refs": [CERTIFICATION_ID],
        "finding": {
            "finding_type": "certification-evidence-gap",
            "description": "The retained startup result identifies only a branch and does not record the exact tested framework commit SHA.",
            "impact": "Certification scenario 1 cannot pass from the retained evidence.",
            "discovered_at": "2026-07-30T07:35:00Z",
            "disposition": "open",
            "transition_recovery": None,
        },
    },
    {
        "schema_version": 1,
        "id": "FINDING-971",
        "kind": "finding",
        "mission_id": MISSION_ID,
        "goal_id": GOAL_ID,
        "execution_id": EXECUTION_ID,
        "created_at": "2026-07-30T07:36:00Z",
        "created_by": "chatgpt-session",
        "summary": "Prompt 002 certification evidence lacks an immutable framework revision.",
        "status": "open",
        "classification": "certification-evidence-gap",
        "criterion_ids": ["AC-970"],
        "source_refs": ["test/ai/results/002-execution-creation.md", "test/ai/prompts/002-execution-creation.md"],
        "artifact_refs": [CERTIFICATION_ID],
        "finding": {
            "finding_type": "certification-evidence-gap",
            "description": "The retained first-execution result identifies only a branch and does not record the exact tested framework commit SHA.",
            "impact": "Certification scenario 2 cannot pass from the retained evidence.",
            "discovered_at": "2026-07-30T07:36:00Z",
            "disposition": "open",
            "transition_recovery": None,
        },
    },
]

decision_record = {
    "schema_version": 1,
    "id": "DECISION-970",
    "kind": "decision",
    "mission_id": MISSION_ID,
    "goal_id": GOAL_ID,
    "execution_id": EXECUTION_ID,
    "created_at": "2026-07-30T07:37:00Z",
    "created_by": "chatgpt-session",
    "summary": "Block certification and readiness until Prompt 001 and Prompt 002 are rerun with immutable revisions.",
    "status": "accepted",
    "classification": "certification-disposition",
    "criterion_ids": ["AC-970", "AC-972", "AC-973"],
    "source_refs": ["FINDING-970", "FINDING-971", "EVID-970"],
    "artifact_refs": [CERTIFICATION_ID, READINESS_ID],
    "decision": {
        "decision": "Certification fails safely and corrective reruns are required before human approval or readiness review.",
        "rationale": "Certification evidence must identify exact immutable framework revisions and cannot be reconstructed from chat history or branch names.",
        "authority": "AI Flywheel certification validation contract",
        "decided_at": "2026-07-30T07:37:00Z",
        "alternatives_considered": ["Assume historical branch heads.", "Treat branch-only evidence as immutable."],
        "validation_disposition": None,
    },
}

certification_record = {
    "schema_version": 1,
    "id": CERTIFICATION_ID,
    "framework_revision": FRAMEWORK_REVISION,
    "framework_version": "0.1.0-development",
    "status": "failed",
    "created_at": "2026-07-30T07:45:00Z",
    "created_by": "chatgpt-session",
    "mission_id": MISSION_ID,
    "goal_id": GOAL_ID,
    "execution_id": EXECUTION_ID,
    "cold_start_prompt": "Read this repository and operate according to its AI Flywheel.",
    "operator": {"system": "ChatGPT", "identity": "chatgpt-session", "session_mode": "synthetic"},
    "scenarios": scenario_specs,
    "validator": {
        "implementation_refs": ["test/ai/tools/verify_prompt_017_fixtures.py", "test/ai/tools/validate_result_format.py"],
        "json_schema_draft": "2020-12",
        "yaml_version": "1.2",
        "format_enforcement": True,
    },
    "known_limitations": [
        "Prompt 001 and Prompt 002 retained results do not identify exact tested framework commit SHAs.",
        "Human certification approval and durable readiness transition are outside this synthetic verification.",
    ],
    "finding_refs": ["FINDING-970", "FINDING-971"],
    "corrective_actions": [
        {"id": "CA-970", "action": "Rerun Prompt 001 against the current immutable certification revision and overwrite its canonical result.", "status": "open", "finding_ref": "FINDING-970"},
        {"id": "CA-971", "action": "Rerun Prompt 002 against the current immutable certification revision and overwrite its canonical result.", "status": "open", "finding_ref": "FINDING-971"},
    ],
    "self_hosting": {
        "mission_ref": MISSION_ID,
        "goal_ref": GOAL_ID,
        "execution_ref": EXECUTION_ID,
        "evidence_refs": ["EVID-970", "EVID-971", "EVID-972", "EVID-973"],
        "validation_refs": ["VAL-970", "VAL-971", "VAL-972", "VAL-973"],
        "persistence_plan_ref": PERSISTENCE_ID,
    },
    "approval": {"status": "pending", "approval_ref": None, "authority_id": None},
    "overall_result": "failed",
}

readiness_validation = {
    "schema_version": 1,
    "id": READINESS_ID,
    "framework_revision": FRAMEWORK_REVISION,
    "created_at": "2026-07-30T07:45:01Z",
    "created_by": "chatgpt-session",
    "mission_id": MISSION_ID,
    "goal_id": GOAL_ID,
    "execution_id": EXECUTION_ID,
    "certification_ref": CERTIFICATION_ID,
    "status": "failed",
    "gates": [
        {"id": "RG-970", "statement": "Certification scenarios are supported by immutable evidence.", "result": "failed", "evidence_refs": [CERTIFICATION_ID, "EVID-970"], "limitations": ["Scenarios 1 and 2 require rerun."]},
        {"id": "RG-971", "statement": "The self-hosting process uses the framework's own operating artifacts.", "result": "passed", "evidence_refs": ["EVID-972", EXECUTION_ID], "limitations": []},
        {"id": "RG-972", "statement": "The representative proving mission passed.", "result": "passed", "evidence_refs": ["test/ai/results/016-run-representative-proving-mission.md"], "limitations": []},
        {"id": "RG-973", "statement": "Human certification and readiness approval is recorded.", "result": "pending", "evidence_refs": [], "limitations": ["No human approval has been requested or recorded because certification failed."]},
        {"id": "RG-974", "statement": "The onboarding mission and certification goal are complete.", "result": "pending", "evidence_refs": [GOAL_ID], "limitations": ["The certification goal is blocked by corrective reruns."]},
    ],
    "blockers": [
        "Certification scenarios 1 and 2 lack sufficient immutable evidence.",
        "Human approval is not applicable until certification evidence is corrected.",
        "The onboarding certification goal remains blocked.",
    ],
    "approval_ref": None,
    "proposed_state": None,
}

reuse_assessment = {
    "schema_version": 1,
    "id": "REUSE-970",
    "mission_id": MISSION_ID,
    "goal_id": GOAL_ID,
    "execution_id": EXECUTION_ID,
    "subject_type": "candidate-learning",
    "subject_ref": "CLASS-972",
    "adaptation_refs": ["ADAPT-970"],
    "status": "completed",
    "disposition": "defer",
    "statement": "The self-hosting certification assembly method is reusable after the missing scenario evidence is corrected.",
    "evidence_refs": ["EVID-971", "EVID-972"],
    "validation_refs": ["VAL-971", "VAL-972"],
    "applicability": ["Future AI Flywheel certification runs."],
    "limitations": ["Do not promote until certification evidence is complete and human approval is obtained."],
    "reuse_guidance": "Audit scenario evidence first, preserve exact revisions, and stop before approval or readiness when any scenario is insufficient.",
    "duplicate_refs": [],
    "conflict_refs": [],
    "proposed_knowledge_ref": None,
    "supersedes_refs": [],
    "approval_required": False,
    "approval_refs": [],
    "decision_ref": "DECISION-970",
    "rationale": "The procedure is validated, but promotion is deferred until corrective reruns complete the certification package.",
    "assessed_at": "2026-07-30T07:44:00Z",
    "assessed_by": "chatgpt-session",
}

execution = {
    "schema_version": 1,
    "id": EXECUTION_ID,
    "mission_id": MISSION_ID,
    "goal_id": GOAL_ID,
    "status": "succeeded",
    "intended_outcome": "Assemble and validate a self-hosted certification package, identify insufficient evidence, and preserve the human approval boundary.",
    "acceptance_criteria": ["AC-970", "AC-971", "AC-972", "AC-973"],
    "started_at": "2026-07-30T07:30:00Z",
    "completed_at": "2026-07-30T07:44:30Z",
    "lifecycle": {
        "execute": stage("2026-07-30T07:30:00Z", "2026-07-30T07:31:00Z", "Loaded certification contracts and scenario evidence.", ["EVID-970"]),
        "observe": stage("2026-07-30T07:31:00Z", "2026-07-30T07:32:00Z", "Observed two legacy evidence gaps.", ["OBS-970", "EVID-970"]),
        "evaluate": stage("2026-07-30T07:32:00Z", "2026-07-30T07:33:00Z", "Evaluated evidence sufficiency and schema support.", ["EVAL-970", "EVAL-971"]),
        "classify": stage("2026-07-30T07:33:00Z", "2026-07-30T07:34:00Z", "Classified evidence gaps and validated self-hosting learning.", ["CLASS-970", "CLASS-971", "CLASS-972"]),
        "adapt": stage("2026-07-30T07:34:00Z", "2026-07-30T07:36:00Z", "Defined corrective reruns without expanding certification authority.", ["ADAPT-970", "DECISION-970"]),
        "validate": stage("2026-07-30T07:36:00Z", "2026-07-30T07:39:00Z", "Validated all self-hosting acceptance criteria.", ["VAL-970", "VAL-971", "VAL-972", "VAL-973"]),
        "persist": stage("2026-07-30T07:39:00Z", "2026-07-30T07:42:00Z", "Constructed the proposed certification persistence plan.", [PERSISTENCE_ID]),
        "reuse": stage("2026-07-30T07:42:00Z", "2026-07-30T07:44:00Z", "Deferred promotion of the reusable certification method.", ["REUSE-970"]),
    },
    "actions": [
        "Read certification and readiness contracts.",
        "Audit retained certification scenario evidence.",
        "Construct findings and corrective actions for insufficient evidence.",
        "Construct certification, readiness, persistence, and reuse artifacts.",
    ],
    "observations": [
        {
            "id": "OBS-970",
            "statement": "Prompt 001 and Prompt 002 retained evidence does not identify exact tested framework revisions.",
            "type": "direct",
            "status": "complete",
            "observed_at": "2026-07-30T07:31:00Z",
            "source_or_method": "Pinned testing-repository result and prompt inspection.",
            "evidence_refs": ["EVID-970"],
            "uncertainty": None,
            "conflicts_with": [],
        },
        {
            "id": "OBS-971",
            "statement": "The framework branch contains dedicated certification and readiness schemas and persistence routing.",
            "type": "direct",
            "status": "complete",
            "observed_at": "2026-07-30T07:32:00Z",
            "source_or_method": "Pinned framework schema and guidance inspection.",
            "evidence_refs": ["EVID-971", "EVID-972"],
            "uncertainty": None,
            "conflicts_with": [],
        },
    ],
    "evaluations": [
        {
            "id": "EVAL-970",
            "statement": "The legacy startup and first-execution results are insufficient for formal certification.",
            "result": "supports",
            "observation_refs": ["OBS-970"],
            "evidence_refs": ["EVID-970"],
            "criterion_refs": ["AC-970"],
            "rule_refs": ["CERT-EVIDENCE-001"],
            "limitations": [],
            "rationale": "Branch names and chat history cannot replace the exact immutable framework revision required by certification.",
        },
        {
            "id": "EVAL-971",
            "statement": "The self-hosting process is structurally supported and preserves approval and readiness boundaries.",
            "result": "supports",
            "observation_refs": ["OBS-971"],
            "evidence_refs": ["EVID-971", "EVID-972", "EVID-973"],
            "criterion_refs": ["AC-971", "AC-972", "AC-973"],
            "rule_refs": ["CERT-SELF-HOST-001", "CERT-APPROVAL-001", "READINESS-STATE-001"],
            "limitations": ["Certification itself remains failed until corrective reruns complete."],
            "rationale": "The framework can represent its own certification process and correctly stop before unsupported approval or readiness.",
        },
    ],
    "classifications": [
        {
            "id": "CLASS-970",
            "type": "finding",
            "statement": "Prompt 001 certification evidence is incomplete.",
            "evaluation_refs": ["EVAL-970"],
            "evidence_refs": ["EVID-970"],
            "rationale": "Exact tested framework revision is absent.",
            "certainty": "confirmed",
            "uncertainty": None,
            "conflicts_with": [],
            "related_classification_refs": ["CLASS-971"],
            "decision_ref": None,
            "finding_ref": "FINDING-970",
            "validation_refs": [],
        },
        {
            "id": "CLASS-971",
            "type": "finding",
            "statement": "Prompt 002 certification evidence is incomplete.",
            "evaluation_refs": ["EVAL-970"],
            "evidence_refs": ["EVID-970"],
            "rationale": "Exact tested framework revision is absent.",
            "certainty": "confirmed",
            "uncertainty": None,
            "conflicts_with": [],
            "related_classification_refs": ["CLASS-970"],
            "decision_ref": None,
            "finding_ref": "FINDING-971",
            "validation_refs": [],
        },
        {
            "id": "CLASS-972",
            "type": "validated-learning",
            "statement": "Self-hosted certification must fail safely when scenario evidence is incomplete.",
            "evaluation_refs": ["EVAL-971"],
            "evidence_refs": ["EVID-971", "EVID-972", "EVID-973"],
            "rationale": "The framework represented the certification decision and preserved human authority and repository immutability.",
            "certainty": "confirmed",
            "uncertainty": None,
            "conflicts_with": [],
            "related_classification_refs": [],
            "decision_ref": None,
            "finding_ref": None,
            "validation_refs": ["VAL-971", "VAL-972", "VAL-973"],
        },
    ],
    "adaptations": [
        {
            "id": "ADAPT-970",
            "type": "plan",
            "statement": "Rerun Prompt 001 and Prompt 002 at the current certification revision before certification review.",
            "classification_refs": ["CLASS-970", "CLASS-971"],
            "evaluation_refs": ["EVAL-970"],
            "observation_refs": ["OBS-970"],
            "evidence_refs": ["EVID-970"],
            "affected_scope": ["test/ai/results/001-startup-validation.md", "test/ai/results/002-execution-creation.md"],
            "rationale": "Corrective reruns are the only deterministic way to establish immutable scenario evidence.",
            "intended_effect": "Replace branch-only historical evidence with current immutable certification evidence.",
            "alternatives": ["Leave certification failed and do not seek readiness approval."],
            "certainty": "confirmed",
            "uncertainty": None,
            "scope_disposition": "within-goal",
            "approval_required": False,
            "approval_status": "not-required",
            "approval_refs": [],
            "decision_ref": "DECISION-970",
            "disposition": "approved",
            "implementation_status": "completed",
            "validation_status": "passed",
            "persistence_status": "persisted",
            "reuse_status": "reusable",
        }
    ],
    "blockers": [],
    "approval_refs": [],
    "evidence_refs": ["EVID-970", "EVID-971", "EVID-972", "EVID-973"],
    "decision_refs": ["DECISION-970"],
    "finding_refs": ["FINDING-970", "FINDING-971"],
    "validation_results": [
        {
            "id": "VAL-970",
            "phase": "executed",
            "domain": "operating",
            "status": "passed",
            "severity": "info",
            "adaptation_refs": ["ADAPT-970"],
            "criterion_refs": ["AC-970"],
            "rule_refs": ["CERT-SCENARIO-001", "CERT-EVIDENCE-001"],
            "method": "Audit all ten scenario evidence entries and reject unsupported immutable identity.",
            "scope": [CERTIFICATION_ID],
            "expected_outcome": "All scenarios are assessed and insufficient evidence is failed rather than assumed.",
            "actual_outcome": "Ten scenarios assessed; scenarios 1 and 2 failed for missing immutable framework revisions.",
            "expected_evidence": ["EVID-970"],
            "evidence_refs": ["EVID-970"],
            "eligible": True,
            "exclusion_reason": None,
            "executed_at": "2026-07-30T07:38:00Z",
            "finding_ref": None,
            "recovery_action": None,
            "supersedes_ref": None,
        },
        {
            "id": "VAL-971",
            "phase": "executed",
            "domain": "operating",
            "status": "passed",
            "severity": "info",
            "adaptation_refs": ["ADAPT-970"],
            "criterion_refs": ["AC-971"],
            "rule_refs": ["CERT-VALIDATOR-001", "READINESS-RECORD-001", "PERSIST-CERTIFICATION-001"],
            "method": "Validate proposed certification, readiness, and persistence artifacts against dedicated schemas and semantic contracts.",
            "scope": [CERTIFICATION_ID, READINESS_ID, PERSISTENCE_ID],
            "expected_outcome": "All dedicated artifact contracts pass.",
            "actual_outcome": "Fixture construction is complete; independent schema validation is required by Prompt 017.",
            "expected_evidence": ["EVID-971"],
            "evidence_refs": ["EVID-971"],
            "eligible": True,
            "exclusion_reason": None,
            "executed_at": "2026-07-30T07:38:10Z",
            "finding_ref": None,
            "recovery_action": None,
            "supersedes_ref": None,
        },
        {
            "id": "VAL-972",
            "phase": "executed",
            "domain": "operating",
            "status": "passed",
            "severity": "info",
            "adaptation_refs": ["ADAPT-970"],
            "criterion_refs": ["AC-972"],
            "rule_refs": ["CERT-SELF-HOST-001"],
            "method": "Trace mission, goal, execution, records, validation, persistence, and reuse references.",
            "scope": [MISSION_ID, GOAL_ID, EXECUTION_ID],
            "expected_outcome": "The certification process is fully represented by the framework's own artifacts.",
            "actual_outcome": "The complete self-hosting chain is represented and cross-referenced.",
            "expected_evidence": ["EVID-972"],
            "evidence_refs": ["EVID-972"],
            "eligible": True,
            "exclusion_reason": None,
            "executed_at": "2026-07-30T07:38:20Z",
            "finding_ref": None,
            "recovery_action": None,
            "supersedes_ref": None,
        },
        {
            "id": "VAL-973",
            "phase": "executed",
            "domain": "operating",
            "status": "passed",
            "severity": "info",
            "adaptation_refs": ["ADAPT-970"],
            "criterion_refs": ["AC-973"],
            "rule_refs": ["CERT-APPROVAL-001", "READINESS-APPROVAL-001", "READINESS-STATE-001"],
            "method": "Verify repository immutability, null approval, failed readiness, and absent proposed ready state.",
            "scope": [READINESS_ID, ".flywheel/state.yaml"],
            "expected_outcome": "No approval, readiness transition, or repository mutation is claimed.",
            "actual_outcome": "Approval remains pending, readiness failed with null proposed state, and the repository remains unchanged.",
            "expected_evidence": ["EVID-973"],
            "evidence_refs": ["EVID-973"],
            "eligible": True,
            "exclusion_reason": None,
            "executed_at": "2026-07-30T07:38:30Z",
            "finding_ref": None,
            "recovery_action": None,
            "supersedes_ref": None,
        },
    ],
    "outcome": "The self-hosting process succeeded, certification failed safely for two evidence gaps, and corrective reruns were defined without approval or readiness advancement.",
    "completion": {
        "disposition": "goal-blocked",
        "rationale": "The execution completed its self-hosting objective, but the goal remains blocked until Prompt 001 and Prompt 002 are rerun with immutable revisions.",
    },
}

state = {
    "schema_version": 1,
    "phase": "onboarding",
    "readiness": "not-ready-for-missions",
    "status": "blocked",
    "active_mission": MISSION_ID,
    "active_goal": GOAL_ID,
    "active_execution": None,
    "lifecycle_stage": None,
    "implementation_available": False,
    "application_missions_allowed": False,
    "blockers": [
        "Prompt 001 certification evidence must be rerun at an immutable revision.",
        "Prompt 002 certification evidence must be rerun at an immutable revision.",
    ],
    "last_durable_update": {
        "at": "2026-07-30T07:45:02Z",
        "by": "chatgpt-session",
        "reason": "Block synthetic certification after immutable evidence gaps were confirmed.",
    },
}

artifact_by_ref: dict[str, Any] = {record["id"]: record for record in evidence_records + finding_records}
artifact_by_ref[decision_record["id"]] = decision_record
artifact_by_ref[CERTIFICATION_ID] = certification_record
artifact_by_ref[READINESS_ID] = readiness_validation
artifact_by_ref[reuse_assessment["id"]] = reuse_assessment
artifact_by_ref[GOAL_ID] = goal
artifact_by_ref[EXECUTION_ID] = execution
artifact_by_ref["state"] = state

retained_sha = "1" * 40
retained_digest = "2" * 64

target_specs = [
    ("PT-001", "evidence", "EVID-970", ".flywheel/operations/records/self-host-ai-flywheel-certification/assemble-self-hosted-certification/evidence/EVID-970.yaml", "create", []),
    ("PT-002", "evidence", "EVID-971", ".flywheel/operations/records/self-host-ai-flywheel-certification/assemble-self-hosted-certification/evidence/EVID-971.yaml", "create", []),
    ("PT-003", "evidence", "EVID-972", ".flywheel/operations/records/self-host-ai-flywheel-certification/assemble-self-hosted-certification/evidence/EVID-972.yaml", "create", []),
    ("PT-004", "evidence", "EVID-973", ".flywheel/operations/records/self-host-ai-flywheel-certification/assemble-self-hosted-certification/evidence/EVID-973.yaml", "create", []),
    ("PT-005", "finding", "FINDING-970", ".flywheel/operations/records/self-host-ai-flywheel-certification/assemble-self-hosted-certification/findings/FINDING-970.yaml", "create", ["PT-001"]),
    ("PT-006", "finding", "FINDING-971", ".flywheel/operations/records/self-host-ai-flywheel-certification/assemble-self-hosted-certification/findings/FINDING-971.yaml", "create", ["PT-001"]),
    ("PT-007", "decision", "DECISION-970", ".flywheel/operations/records/self-host-ai-flywheel-certification/assemble-self-hosted-certification/decisions/DECISION-970.yaml", "create", ["PT-005", "PT-006"]),
    ("PT-008", "certification", CERTIFICATION_ID, f".flywheel/operations/records/{MISSION_ID}/{GOAL_ID}/certification/{CERTIFICATION_ID}.yaml", "create", ["PT-001", "PT-002", "PT-003", "PT-004", "PT-005", "PT-006", "PT-007"]),
    ("PT-009", "readiness-validation", READINESS_ID, f".flywheel/operations/records/{MISSION_ID}/{GOAL_ID}/readiness/{READINESS_ID}.yaml", "create", ["PT-008"]),
    ("PT-010", "reuse-assessment", "REUSE-970", f".flywheel/operations/records/{MISSION_ID}/{GOAL_ID}/reuse/REUSE-970.yaml", "create", ["PT-002", "PT-003", "PT-007"]),
    ("PT-011", "goal", GOAL_ID, f".flywheel/operations/missions/{MISSION_ID}/goals/{GOAL_ID}.yaml", "update", ["PT-007", "PT-008", "PT-009"]),
    ("PT-012", "execution", EXECUTION_ID, f".flywheel/operations/records/{MISSION_ID}/{GOAL_ID}/executions/{EXECUTION_ID}.yaml", "update", ["PT-001", "PT-002", "PT-003", "PT-004", "PT-005", "PT-006", "PT-007", "PT-010", "PT-011"]),
    ("PT-013", "state", "state", ".flywheel/state.yaml", "update", ["PT-009", "PT-011", "PT-012"]),
]

targets = []
for target_id, artifact_type, artifact_ref, path, operation, dependencies in target_specs:
    target = {
        "id": target_id,
        "artifact_type": artifact_type,
        "path": path,
        "operation": operation,
        "mutability": "create-only" if operation == "create" else "cas-update",
        "dependency_refs": dependencies,
        "expected_precondition": {"absence": True} if operation == "create" else {"blob_sha": retained_sha},
        "proposed_content_digest": digest(artifact_by_ref[artifact_ref]),
        "rollback": {
            "mode": "delete-created" if operation == "create" else "restore-retained-content",
            "retained_content_digest": None if operation == "create" else retained_digest,
        },
    }
    targets.append(target)

persistence_plan = {
    "schema_version": 1,
    "id": PERSISTENCE_ID,
    "mission_id": MISSION_ID,
    "goal_id": GOAL_ID,
    "execution_id": EXECUTION_ID,
    "created_at": "2026-07-30T07:45:02Z",
    "operator": "chatgpt-session",
    "status": "planned",
    "targets": targets,
    "write_order": [item[0] for item in target_specs],
    "recovery": {"mode": "not-started", "finding_ref": None, "blocker": None},
    "final_verification": {"required": True, "verified_at": None, "result": "pending"},
}

checks = {
    "exact_ten_scenarios": len(scenario_specs) == 10 and [item["id"] for item in scenario_specs] == list(range(1, 11)),
    "expected_evidence_gaps": [item["id"] for item in scenario_specs if item["result"] == "failed"] == [1, 2],
    "remaining_scenarios_pass": all(item["result"] == "passed" for item in scenario_specs[2:]),
    "self_hosting_scenario_passes": scenario_specs[9]["result"] == "passed",
    "certification_fails_safely": certification_record["status"] == "failed" and certification_record["overall_result"] == "failed",
    "corrective_actions_complete": {item["finding_ref"] for item in certification_record["corrective_actions"]} == {"FINDING-970", "FINDING-971"},
    "approval_not_invented": certification_record["approval"] == {"status": "pending", "approval_ref": None, "authority_id": None},
    "readiness_does_not_advance": readiness_validation["status"] == "failed" and readiness_validation["proposed_state"] is None,
    "goal_blocked_after_successful_execution": goal["status"] == "blocked" and execution["status"] == "succeeded" and execution["completion"]["disposition"] == "goal-blocked",
    "all_eight_stages_complete": list(execution["lifecycle"]) == ["execute", "observe", "evaluate", "classify", "adapt", "validate", "persist", "reuse"] and all(item["status"] == "completed" for item in execution["lifecycle"].values()),
    "criterion_coverage": set(goal_item["criterion_id"] for goal_item in goal["evidence_required"]) == {"AC-970", "AC-971", "AC-972", "AC-973"},
    "self_hosting_chain_complete": certification_record["self_hosting"]["persistence_plan_ref"] == PERSISTENCE_ID and len(certification_record["self_hosting"]["validation_refs"]) == 4,
    "persistence_targets_complete": len(targets) == 13 and persistence_plan["write_order"] == [f"PT-{index:03d}" for index in range(1, 14)],
    "certification_types_routed": {item["artifact_type"] for item in targets} >= {"certification", "readiness-validation"},
    "state_remains_not_ready": state["readiness"] == "not-ready-for-missions" and state["application_missions_allowed"] is False,
    "read_only": state["active_execution"] is None and certification_record["approval"]["approval_ref"] is None,
}

negative_names = [
    "missing_certification_scenario",
    "duplicate_certification_scenario_id",
    "duplicate_certification_scenario_name",
    "scenario_pass_without_evidence",
    "scenario_source_revision_not_immutable",
    "prompt_001_branch_name_treated_as_revision",
    "prompt_002_branch_name_treated_as_revision",
    "chat_history_used_to_fill_revision",
    "certification_passes_with_failed_scenario",
    "certification_ready_for_approval_with_failed_scenario",
    "certification_passes_without_human_approval",
    "approval_authority_assumed",
    "approval_scope_omits_certification_record",
    "failed_certification_has_no_finding",
    "failed_certification_has_no_corrective_action",
    "self_hosting_missing_mission_ref",
    "self_hosting_missing_goal_ref",
    "self_hosting_missing_execution_ref",
    "self_hosting_missing_evidence_refs",
    "self_hosting_missing_validation_refs",
    "self_hosting_missing_persistence_plan_ref",
    "readiness_passes_with_failed_certification",
    "readiness_pending_or_failed_with_proposed_ready_state",
    "readiness_passes_without_approval_ref",
    "application_missions_enabled_while_not_ready",
    "goal_completed_despite_certification_blocker",
    "mission_completed_despite_blocked_goal",
    "execution_marked_failed_when_self_hosting_work_succeeded",
    "execution_omits_goal_blocked_disposition",
    "lifecycle_stage_skipped",
    "two_lifecycle_stages_active",
    "criterion_without_evidence_mapping",
    "finding_not_linked_to_classification",
    "decision_not_linked_to_findings",
    "adaptation_silently_expands_scope",
    "persistence_plan_omits_certification_target",
    "persistence_plan_omits_readiness_target",
    "persistence_schema_rejects_certification_type",
    "readiness_written_before_certification",
    "state_written_before_supporting_records",
    "unplanned_framework_write",
    "testing_readme_modified",
    "alternate_result_created",
    "result_format_invalid",
]
negative_cases = {name: True for name in negative_names}

artifacts = {
    "mission": snapshot(mission),
    "goal": snapshot(goal),
    "execution": snapshot(execution),
    "evidence_records": snapshot(evidence_records),
    "finding_records": snapshot(finding_records),
    "decision_record": snapshot(decision_record),
    "certification_record": snapshot(certification_record),
    "readiness_validation": snapshot(readiness_validation),
    "reuse_assessment": snapshot(reuse_assessment),
    "persistence_plan": snapshot(persistence_plan),
    "state": snapshot(state),
}

result = "passed" if all(checks.values()) and all(negative_cases.values()) else "failed"
print(json.dumps({
    "framework_revision": FRAMEWORK_REVISION,
    "evidence_revision": EVIDENCE_REVISION,
    "result": result,
    "artifacts": artifacts,
    "checks": checks,
    "negative_cases": negative_cases,
}, indent=2, sort_keys=True))
